// AUTO-GENERATED by @quartal/plugin — do not edit. Regenerated from the plugin's prompts on build.

import * as m0 from "../prompts/GreetingPrompts.ts";

/** Static prompt-module registry keyed by file name (basename without extension). */
export const promptModules: Record<string, Record<string, unknown>> = {
  "GreetingPrompts": m0 as unknown as Record<string, unknown>,
};
