import { cpSync, existsSync, mkdirSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import { info, step } from "./log.mjs";
import { readJson } from "./project.mjs";
import { run } from "./run.mjs";
import { resolveWorkspaceDeps } from "./workspaceDeps.mjs";

/** Directory (relative to the repo root) holding the generated staging trees. Gitignored. */
export const STAGE_ROOT = ".deploy";

/**
 * Entries never copied into a stage: build output, installed packages, generated plugin artifacts
 * (regenerated by `astro build`) and anything a previous staging run wrote.
 */
const SKIP_ENTRIES = new Set([
  ".astro",
  ".deploy",
  ".git",
  ".turbo",
  ".wrangler",
  "dist",
  "node_modules",
  "vendor",
]);

/** Paths, relative to the plugin root, that are generated at build time and must not be copied. */
const SKIP_PATHS = new Set([join("src", "qrtl-plugin")]);

function copyPluginSources(from, to) {
  mkdirSync(to, { recursive: true });
  for (const entry of readdirSync(from, { withFileTypes: true })) {
    if (SKIP_ENTRIES.has(entry.name)) continue;
    cpSync(join(from, entry.name), join(to, entry.name), {
      recursive: true,
      filter: (src) => !SKIP_PATHS.has(relative(from, src)),
    });
  }
}

/**
 * Builds the staged manifest: workspace dependencies become resolvable specifiers, the adapter for
 * this target is added, and `start` is wired up for platforms that run the built server themselves.
 */
function writeStagedManifest({ project, target, repoRoot, stageDir, linkMode }) {
  const pkg = readJson(join(stageDir, "package.json"));
  resolveWorkspaceDeps({ pkg, repoRoot, stageDir, linkMode });

  pkg.dependencies = { ...pkg.dependencies, ...target.dependencies };
  pkg.scripts = { ...pkg.scripts, start: target.startCommand ?? "node ./dist/server/entry.mjs" };
  pkg.engines = { ...pkg.engines, node: pkg.engines?.node ?? ">=22.0.0" };

  // The stage is a single standalone package — workspace/monorepo metadata would only confuse the
  // platform builders that run `npm install` in it.
  delete pkg.packageManager;
  delete pkg.pnpm;

  writeFileSync(join(stageDir, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`);
}

/**
 * Replaces the plugin's Astro config with a generated one that keeps every setting from the
 * original (integrations, output, widgets) and swaps in the adapter this target needs. The original
 * is kept alongside as `astro.config.base.<ext>` and imported by the generated file, so a plugin
 * never has to know how it will be hosted.
 */
function writeAstroConfig({ project, target, stageDir }) {
  const original = project.astroConfig;
  const extension = original.slice("astro.config.".length);
  const baseName = `astro.config.base.${extension}`;
  renameSync(join(stageDir, original), join(stageDir, baseName));

  const source = [
    `// AUTO-GENERATED by deployment/deploy.mjs for the "${target.id}" target — do not edit.`,
    `// The plugin's own config is kept as ./${baseName}; only the adapter is replaced here.`,
    `import { defineConfig } from "astro/config";`,
    ...target.astroImports,
    `import base from "./${baseName}";`,
    ``,
    `export default defineConfig({`,
    `  ...base,`,
    ...target.astroOverrides.map((line) => `  ${line}`),
    `});`,
    ``,
  ].join("\n");

  writeFileSync(join(stageDir, "astro.config.mjs"), source);
  return baseName;
}

/**
 * Materialises a self-contained deployable copy of a sample plugin under
 * `.deploy/<target>/<project>/`.
 *
 * Staging exists because the samples are pnpm-workspace members: they depend on `@quartal/*` via
 * `workspace:*` and share the repo's `node_modules`, neither of which any hosting platform can
 * resolve. The stage is a plain npm package that installs and builds on its own.
 * @param options `{ project, target, repoRoot, linkMode, dryRun }`.
 */
export function createStage({ project, target, repoRoot, linkMode, dryRun }) {
  const stageDir = join(repoRoot, STAGE_ROOT, target.id, project.name);

  step(`Staging ${project.name} for ${target.title} in ${relative(repoRoot, stageDir)}/`);
  if (dryRun) {
    info(`(dry run) would copy ${relative(repoRoot, project.dir)}/ and rewrite it for ${target.title}`);
    return { dir: stageDir, dryRun: true };
  }

  rmSync(stageDir, { recursive: true, force: true });
  copyPluginSources(project.dir, stageDir);
  writeStagedManifest({ project, target, repoRoot, stageDir, linkMode });
  const baseConfig = writeAstroConfig({ project, target, stageDir });
  info(`astro.config.mjs generated (adapter: ${target.adapterName}, base: ${baseConfig})`);

  for (const [path, contents] of Object.entries(target.files?.({ project }) ?? {})) {
    mkdirSync(dirname(join(stageDir, path)), { recursive: true });
    writeFileSync(join(stageDir, path), contents);
    info(`wrote ${path}`);
  }

  return { dir: stageDir };
}

/**
 * Installs and builds inside a stage. Only needed for platforms that upload a finished artifact
 * (Cloudflare); Deno Deploy and Railway build the uploaded sources themselves, so there the build
 * is opt-in via `--build` as a pre-flight check.
 * @param options `{ stageDir, dryRun }`.
 */
export function buildStage({ stageDir, dryRun }) {
  step("Installing dependencies and building in the stage");
  const lock = existsSync(join(stageDir, "package-lock.json"));
  run("npm", [lock ? "ci" : "install", "--no-audit", "--no-fund"], { cwd: stageDir, dryRun });
  run("npm", ["run", "build"], { cwd: stageDir, dryRun });
}
