// The analysis layer consumes shared types from the published @quartal/plugin-core package.
// This barrel keeps the relative import path (`../model/index.ts`) stable for the rest of src/.
export type { AuthContext } from "./AuthContext.ts";
export { defineQrtlConfig } from "./QrtlConfig.ts";
export type { QrtlConfig } from "./QrtlConfig.ts";
export type {
  ExecuteFn,
  FetchWidgetHtml,
  McpServerOptions,
  PluginAppConfig,
  ToolModuleRegistry,
  WidgetEntry,
} from "./web-app/index.ts";
export type {
  AgentCatalogEntry,
  AgentCatalogUrls,
  AgentColor,
  AgentDefinition,
  AgentEffort,
  AgentIsolation,
  AgentMcpServer,
  AgentModelRef,
  AgentPermissionMode,
  AgentsCatalog,
  AgentsCatalogResponse,
  AgentToolKind,
  AgentToolRef,
  Avatar,
  AvatarEntityType,
  AvatarPictureType,
  BootstrapColor,
  ClaudeColor,
  CodeArrayType,
  CodeClass,
  CodeFile,
  CodeFunction,
  CodeOrSystemType,
  CodePropOrParam,
  CodeType,
  McpCatalog,
  McpCatalogEntry,
  McpCatalogTool,
  McpPromptDescriptor,
  McpPromptsDocument,
  McpToolDescriptor,
  PluginAgentSummary,
  PluginIcon,
  PluginInfo,
  PluginLinks,
  PluginManifest,
  PluginPromptEntry,
  PluginRepository,
  PluginSkillSummary,
  PluginToolEntry,
  PluginToolExposure,
  PluginToolGroup,
  PluginToolParameter,
  PluginWidgetEntry,
  PromptArgument,
  PromptMessage,
  PromptResponse,
  PromptResult,
  QuartalPluginContext,
  SkillCatalogEntry,
  SkillCatalogUrls,
  SkillEntry,
  SkillFileEntry,
  SkillFileWithUrl,
  SkillFrontmatter,
  SkillsCatalog,
  SkillsCatalogResponse,
  SystemType,
  WidgetCatalogEntry,
  WidgetCsp,
} from "@quartal/plugin-core";
// MCP specification types (copied into plugin-core's model/mcp-spec, original names).
export type {
  Annotations,
  AudioContent,
  BaseMetadata,
  BlobResourceContents,
  ContentBlock,
  EmbeddedResource,
  ImageContent,
  Resource,
  ResourceContents,
  ResourceLink,
  Role,
  TextContent,
  TextResourceContents,
} from "@quartal/plugin-core";
