// The analysis layer consumes shared types from the published @quartal/plugin-core package.
// This barrel keeps the relative import path (`../model/index.ts`) stable for the rest of src/.
export type { AuthContext } from "./AuthContext.ts";
export { defineQrtlConfig } from "./QrtlConfig.ts";
export type { QrtlConfig } from "./QrtlConfig.ts";
export type { ExecuteFn, McpServerOptions, PluginAppConfig, ToolModuleRegistry } from "./web-app/index.ts";
export type {
  Avatar,
  AvatarEntityType,
  AvatarPictureType,
  CodeArrayType,
  CodeClass,
  CodeFile,
  CodeFunction,
  CodeOrSystemType,
  CodePropOrParam,
  CodeType,
  McpCatalog,
  McpCatalogEntry,
  McpCatalogTool,
  McpToolDescriptor,
  PluginIcon,
  PluginInfo,
  PluginLinks,
  PluginManifest,
  PluginRepository,
  PluginSkillSummary,
  PluginToolEntry,
  PluginToolExposure,
  PluginToolGroup,
  PluginToolParameter,
  PluginWidgetEntry,
  QuartalPluginContext,
  SkillCatalogEntry,
  SkillCatalogUrls,
  SkillEntry,
  SkillFileEntry,
  SkillFileWithUrl,
  SkillFrontmatter,
  SkillsCatalog,
  SkillsCatalogResponse,
  SystemType,
  WidgetCatalogEntry,
  WidgetCsp,
} from "@quartal/plugin-core";
