import type { CodeFile } from "../model/index.ts";

/** Options for {@link buildToolsRegistrySource}. */
export interface ToolsRegistryOptions {
  /**
   * Relative import base from the generated registry file to the tools directory.
   * Default `"../tools"` — i.e. the registry lives next to the other artifacts in `qrtl-plugin/`
   * (or `src/qrtl-plugin/`) and the tool classes in the sibling `tools/` (or `src/tools/`).
   */
  importBase?: string;
}

/** The base file name (no extension) for a tool source file. */
function toolFileName(file: CodeFile): string {
  const normalized = file.path.replace(/\\/g, "/");
  const last = normalized.split("/").pop() ?? file.name;
  return last.replace(/\.ts$/, "");
}

/**
 * Builds the source of a static tool-module registry. This replaces the former runtime
 * `import(toFileUrl(join(baseDir, "tools", fileName + ".ts")))` dynamic path-import, which does not
 * survive Vite/edge bundling. `execute(fileName, className, method, …)` looks the class up as
 * `toolModules[fileName][className]`.
 *
 * Only files that expose classes are included (system/system-type and imported-type files are skipped).
 * @param codeFiles Analyzed code files (from the analyzer or `tools.json`).
 * @param options Import-path options.
 */
export function buildToolsRegistrySource(codeFiles: CodeFile[], options?: ToolsRegistryOptions): string {
  const importBase = (options?.importBase ?? "../tools").replace(/\/+$/, "");

  const toolFiles = codeFiles.filter(
    (f) => f.path !== "__system__.ts" && !f.path.startsWith("types/") && (f.classes?.length ?? 0) > 0,
  );
  const names = [...new Set(toolFiles.map(toolFileName))].sort((a, b) => a.localeCompare(b));

  const lines: string[] = [
    "// AUTO-GENERATED by @quartal/plugin — do not edit. Regenerated from the plugin's tools on build.",
    "",
  ];
  names.forEach((name, i) => lines.push(`import * as m${i} from "${importBase}/${name}.ts";`));
  lines.push("");
  lines.push("/** Static tool-module registry keyed by file name (basename without extension). */");
  lines.push("export const toolModules: Record<string, Record<string, unknown>> = {");
  names.forEach((name, i) => lines.push(`  ${JSON.stringify(name)}: m${i} as unknown as Record<string, unknown>,`));
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}
