import { fail, info, step, warn } from "../lib/log.mjs";
import { hasCommand, run } from "../lib/run.mjs";

/** Astro adapter for Cloudflare Workers, and the wrangler version it peers with. */
const CLOUDFLARE_ADAPTER = "^14.2.4";
const WRANGLER = "^4.125.0";

/**
 * Compatibility date for the Worker. Must be >= 2025-09-01 for `node:fs` to exist at all (the
 * runtime's disk-read *fallbacks* import it, even though a bundled plugin never calls them).
 */
const COMPATIBILITY_DATE = "2026-08-01";

/**
 * Cloudflare Workers target.
 *
 * Unlike Railway and Vercel this one uploads a *finished* bundle: wrangler ships the built
 * Worker, so the build runs locally and `buildsLocally` is true.
 *
 * A Worker has no real filesystem, and needs none: the codegen's `artifacts.ts` module carries the
 * generated metadata, manifest, qrtl.config, widget entries and the skills/agents/README file map
 * inside the bundle, the docs UI shell is fetched from the Quartal Plugins website at runtime, and
 * `public/` ships as Workers static assets. Verified in `wrangler dev`: /plugin.json, OpenAPI,
 * skills (catalog, files, zips), agents, /plugin.zip, MCP tools/list, REST execution, widget pages
 * and the docs shell all serve. Requires `@quartal/plugin` > 0.8.0 — until that is published,
 * stage with `--link local`.
 *
 * A real (authenticated) deploy has not been exercised yet — treat the first one as the test.
 */
export default {
  id: "cloudflare",
  title: "Cloudflare Workers",
  adapterName: "@astrojs/cloudflare",
  dependencies: { "@astrojs/cloudflare": CLOUDFLARE_ADAPTER, wrangler: WRANGLER },
  startCommand: "wrangler dev",
  buildsLocally: true,
  astroImports: [`import cloudflare from "@astrojs/cloudflare";`],
  astroOverrides: [`adapter: cloudflare(),`],

  files: ({ project }) => ({
    "wrangler.jsonc": `${JSON.stringify(
      {
        $schema: "node_modules/wrangler/config-schema.json",
        name: project.app,
        compatibility_date: COMPATIBILITY_DATE,
        compatibility_flags: ["nodejs_compat"],
        observability: { enabled: true },
      },
      null,
      2,
    )}\n`,
    ".gitignore": `node_modules/\ndist/\n.astro/\n.wrangler/\n`,
    "DEPLOY.md": [
      `# ${project.name} — Cloudflare Workers stage`,
      ``,
      `Generated by \`deployment/deploy.mjs cloudflare ${project.name}\`. Do not edit; re-run the script.`,
      ``,
      `wrangler uploads the Worker bundle built here by \`@astrojs/cloudflare\`. Verify locally with`,
      `\`npx wrangler dev\`. Requires @quartal/plugin > 0.8.0 (stage with \`--link local\` until published).`,
      ``,
    ].join("\n"),
  }),

  /** Uploads the locally built Worker bundle with wrangler. */
  deploy({ stageDir, app, dryRun, extraArgs }) {
    step(`Deploying Worker "${app}"`);
    if (!dryRun && !hasCommand("npx", ["--version"])) fail("npx not found — Node 22+ is required.");
    if (!dryRun && !process.env.CLOUDFLARE_API_TOKEN) {
      warn("CLOUDFLARE_API_TOKEN is not set — the CLI will use the login from `npx wrangler login`.");
    }
    info("wrangler uploads the bundle @astrojs/cloudflare just built.");
    run("npx", ["wrangler", "deploy", ...extraArgs], { cwd: stageDir, dryRun });
  },

  notes: [
    "Requires @quartal/plugin > 0.8.0 — until it is on npm, stage with `--link local`",
    "(after `pnpm build:libs`): the published 0.8.0 runtime reads from disk and 500s in a Worker.",
    "Verify locally first: `--stage-only`, then `npx wrangler dev` in the stage.",
    "Authenticate with `npx wrangler login`, or set CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID.",
    "The adapter can use a SESSION KV binding (Astro sessions). Plugins don't use sessions, so none",
    "is configured; add a KV namespace id to wrangler.jsonc if your own pages need them.",
    "The first authenticated deploy is still unverified — treat it as the real test.",
  ],
};
