import { fail, info, step, warn } from "../lib/log.mjs";
import { hasCommand, run } from "../lib/run.mjs";

/** Astro adapter for Cloudflare Workers, and the wrangler version it peers with. */
const CLOUDFLARE_ADAPTER = "^14.2.4";
const WRANGLER = "^4.125.0";

/**
 * Compatibility date for the Worker. Must be >= 2025-09-01 for `node:fs` to exist at all, which
 * the Quartal plugin runtime needs (see the caveat below and `deployment/README.md`).
 */
const COMPATIBILITY_DATE = "2026-08-01";

/**
 * Cloudflare Workers target.
 *
 * Unlike Railway and Deno Deploy this one uploads a *finished* bundle: wrangler ships the built
 * Worker, so the build runs locally and `buildsLocally` is true.
 *
 * KNOWN BLOCKER — a Worker has no real filesystem. Workers expose `node:fs` over a virtual FS whose
 * `process.cwd()` is `/bundle`, containing only the modules that ended up in the Worker bundle. The
 * plugin runtime instead reads `package.json`, `README.md`, `qrtl.config.*`, `src/qrtl-plugin/*.json`,
 * `skills/`, `agents/` and `public/` from the plugin root on every request, and resolves the docs SPA
 * out of `@quartal/plugin` with `createRequire().resolve()`.
 *
 * The build succeeds and the bundle is valid (verified with `wrangler deploy --dry-run`), but the
 * Worker throws while assembling the Hono app: `getPkgDocsWebStaticRoot()` cannot resolve
 * `@quartal/plugin`, and its `import.meta.url` fallback is not a usable base URL, so *every* route
 * answers 500. Reproduce it with `npx wrangler dev` inside the stage.
 *
 * Fixing this is a change in `@quartal/plugin` (bundle-time artifacts instead of request-time disk
 * reads — see deployment/README.md), not something a deployment script can paper over, so this
 * target stages and builds but refuses to deploy unless you pass --force.
 */
export default {
  id: "cloudflare",
  title: "Cloudflare Workers",
  adapterName: "@astrojs/cloudflare",
  dependencies: { "@astrojs/cloudflare": CLOUDFLARE_ADAPTER, wrangler: WRANGLER },
  startCommand: "wrangler dev",
  buildsLocally: true,
  astroImports: [`import cloudflare from "@astrojs/cloudflare";`],
  astroOverrides: [`adapter: cloudflare(),`],

  files: ({ project }) => ({
    "wrangler.jsonc": `${JSON.stringify(
      {
        $schema: "node_modules/wrangler/config-schema.json",
        name: project.app,
        compatibility_date: COMPATIBILITY_DATE,
        compatibility_flags: ["nodejs_compat"],
        observability: { enabled: true },
      },
      null,
      2,
    )}\n`,
    ".gitignore": `node_modules/\ndist/\n.astro/\n.wrangler/\n`,
    "DEPLOY.md": [
      `# ${project.name} — Cloudflare Workers stage`,
      ``,
      `Generated by \`deployment/deploy.mjs cloudflare ${project.name}\`. Do not edit; re-run the script.`,
      ``,
      `Experimental. A Worker has no filesystem, and the Quartal plugin runtime reads its`,
      `metadata, skills and docs assets from disk at request time. See "Cloudflare Workers" in`,
      `\`deployment/README.md\` for what has to change in \`@quartal/plugin\` first.`,
      ``,
    ].join("\n"),
  }),

  /** Refuses by default: see the caveat on this module. */
  deploy({ stageDir, app, dryRun, extraArgs, force }) {
    if (!force) {
      fail([
        "Cloudflare Workers deploys are blocked for Quartal plugins (use --force to override).",
        "",
        "A Worker has no filesystem, but the plugin runtime reads package.json, qrtl.config.*,",
        "src/qrtl-plugin/*.json, skills/, agents/ and public/ from the plugin root on every request.",
        "The Worker builds and uploads fine, then answers 500 on every route because it cannot",
        "resolve the docs SPA out of @quartal/plugin.",
        "",
        "The stage is at " + stageDir + " — run `npx wrangler dev` there to see the failure.",
        "See the Cloudflare section of deployment/README.md for the fix needed in @quartal/plugin.",
      ].join("\n"));
    }

    step(`Deploying Worker "${app}" (forced)`);
    warn("Forced deploy: every route will answer 500 until @quartal/plugin stops reading from disk.");
    if (!dryRun && !hasCommand("npx", ["--version"])) fail("npx not found — Node 22+ is required.");
    info("wrangler uploads the bundle @astrojs/cloudflare just built.");
    run("npx", ["wrangler", "deploy", ...extraArgs], { cwd: stageDir, dryRun });
  },

  notes: [
    "Blocked, not broken: read the Cloudflare section of deployment/README.md before using this.",
    "`--stage-only` builds a valid Worker bundle — that plus `npx wrangler dev` is the harness for",
    "fixing the runtime, and `npx wrangler deploy --dry-run` validates the upload offline.",
    "Authenticate with `npx wrangler login`, or set CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID.",
    "The adapter requests a SESSION KV binding; a real deploy needs a KV namespace id for it.",
  ],
};
