import { fail, info, step } from "../lib/log.mjs";
import { hasCommand, run } from "../lib/run.mjs";

/** Astro adapter for the Deno runtime. Maintained by Deno, not by Astro. */
const DENO_ADAPTER = "^0.6.0";

/**
 * Deno Deploy target.
 *
 * Deno Deploy builds the uploaded sources on the platform (`npm install` -> `npm run build`) and
 * then runs the built entrypoint under Deno with a real `node_modules` tree, so the plugin
 * runtime's `node:fs` reads (`skills/`, `public/`, `src/qrtl-plugin/*.json`, the docs SPA resolved
 * out of `@quartal/plugin`) all resolve the same way they do under Node.
 *
 * `deployctl` is deliberately not used: Deno Deploy Classic shut down in July 2026 and the current
 * platform is driven by the `deno deploy` subcommand built into the Deno CLI (Deno >= 2.4.2).
 */
export default {
  id: "deno",
  title: "Deno Deploy",
  adapterName: "@deno/astro-adapter",
  dependencies: { "@deno/astro-adapter": DENO_ADAPTER },
  /** The adapter's generated entry starts its own `Deno.serve` on import. */
  startCommand: "deno run --allow-net --allow-read --allow-env ./dist/server/entry.mjs",
  buildsLocally: false,
  astroImports: [`import deno from "@deno/astro-adapter";`],
  astroOverrides: [`adapter: deno(),`],

  files: ({ project }) => ({
    // `deno deploy` reads org/app/entrypoint from here, so re-deploys need no flags at all.
    // `nodeModulesDir: "manual"` tells Deno to use the node_modules the platform's install step
    // produced instead of resolving npm specifiers itself.
    "deno.json": `${JSON.stringify(
      {
        nodeModulesDir: "manual",
        tasks: { build: "npm run build", start: "deno run --allow-net --allow-read --allow-env ./dist/server/entry.mjs" },
        deploy: { org: project.org, app: project.app, entrypoint: "dist/server/entry.mjs" },
      },
      null,
      2,
    )}\n`,
    ".gitignore": `node_modules/\ndist/\n.astro/\n`,
    "DEPLOY.md": [
      `# ${project.name} — Deno Deploy stage`,
      ``,
      `Generated by \`deployment/deploy.mjs deno ${project.name}\`. Do not edit; re-run the script.`,
      ``,
      `The platform runs \`npm install\` then \`npm run build\`, and serves`,
      `\`dist/server/entry.mjs\` in dynamic runtime mode. The adapter's server listens on port 8085`,
      `locally; Deno Deploy routes traffic to whatever port \`Deno.serve\` binds.`,
      ``,
    ].join("\n"),
  }),

  /**
   * Creates the app on the first run (`--create`) and deploys on every run. Build commands are
   * pinned explicitly rather than relying on framework auto-detection, so a detection change on
   * the platform cannot silently alter how a plugin is built.
   */
  deploy({ stageDir, app, org, region, dryRun, extraArgs, create }) {
    if (!dryRun && !hasCommand("deno")) {
      fail("Deno CLI not found. Install it from https://deno.com (Deno >= 2.4.2 has `deno deploy`).");
    }
    if (!org) fail("No Deno Deploy org. Set `deploy.org` in the plugin's qrtl.config.ts or pass --org.");

    if (create) {
      step(`Creating Deno Deploy app "${app}" in org "${org}"`);
      run("deno", [
        "deploy", "create",
        "--org", org,
        "--app", app,
        "--source", "local",
        "--do-not-use-detected-build-config",
        "--install-command", "npm install",
        "--build-command", "npm run build",
        "--pre-deploy-command", "echo staged",
        "--runtime-mode", "dynamic",
        "--entrypoint", "dist/server/entry.mjs",
        "--build-timeout", "15",
        "--build-memory-limit", "2048",
        "--region", region,
        ...extraArgs,
      ], { cwd: stageDir, dryRun });
      info("`deno deploy create` also performs the first deploy.");
      return;
    }

    step(`Deploying to Deno Deploy app "${app}" (org "${org}")`);
    run("deno", ["deploy", "--org", org, "--app", app, "--prod", ...extraArgs], { cwd: stageDir, dryRun });
  },

  notes: [
    "Run once with --create to create the app; after that plain runs deploy to production.",
    "Authenticate with `deno deploy login`, or set DENO_DEPLOY_TOKEN in CI.",
    "Regions: us | eu | global (--region, create only).",
  ],
};
