import { fail, info, step, warn } from "../lib/log.mjs";
import { hasCommand, run } from "../lib/run.mjs";

/** Astro adapter for Railway. Bump alongside the samples' own `@astrojs/node` dependency. */
const NODE_ADAPTER = "^11.1.4";

/**
 * Railway target: a long-running Node container.
 *
 * Railway builds the uploaded sources itself (Railpack detects Node, runs `npm install` +
 * `npm run build`, then the `start` script), so the whole plugin tree — `skills/`, `public/`,
 * `README.md`, `qrtl.config.ts` and the generated `src/qrtl-plugin/` — is present on disk at
 * request time. That is exactly what the Quartal plugin runtime expects, which makes Railway the
 * zero-caveat target of the three.
 */
export default {
  id: "railway",
  title: "Railway",
  adapterName: "@astrojs/node (standalone)",
  dependencies: { "@astrojs/node": NODE_ADAPTER },
  /** Railway injects `PORT`; `host: true` below makes the server bind `0.0.0.0`. */
  startCommand: "node ./dist/server/entry.mjs",
  buildsLocally: false,
  astroImports: [`import node from "@astrojs/node";`],
  astroOverrides: [
    `adapter: node({ mode: "standalone" }),`,
    `// Railway routes to the container's PORT, so the server must not bind localhost only.`,
    `server: { ...base.server, host: true },`,
  ],

  files: ({ project }) => ({
    "railway.json": `${JSON.stringify(
      {
        $schema: "https://railway.com/railway.schema.json",
        build: { buildCommand: "npm run build" },
        deploy: {
          startCommand: "node ./dist/server/entry.mjs",
          restartPolicyType: "ON_FAILURE",
          restartPolicyMaxRetries: 10,
          healthcheckPath: "/plugin.json",
        },
      },
      null,
      2,
    )}\n`,
    ".gitignore": `node_modules/\ndist/\n.astro/\n`,
    "DEPLOY.md": [
      `# ${project.name} — Railway stage`,
      ``,
      `Generated by \`deployment/deploy.mjs railway ${project.name}\`. Do not edit; re-run the script.`,
      ``,
      `Railway builds this directory with Railpack: \`npm install\` -> \`npm run build\` ->`,
      `\`npm start\`. \`PORT\` comes from Railway, and the health check hits \`/plugin.json\`.`,
      ``,
    ].join("\n"),
  }),

  /**
   * Uploads the stage with the Railway CLI. The CLI needs to know which service to deploy to:
   * either run `railway link` once in this repo, or set `RAILWAY_TOKEN` to a project token.
   */
  deploy({ stageDir, app, dryRun, extraArgs }) {
    step(`Deploying to Railway service "${app}"`);
    if (!dryRun && !hasCommand("railway")) {
      fail("Railway CLI not found. Install it with `npm i -g @railway/cli`, then `railway login`.");
    }
    if (!dryRun && !process.env.RAILWAY_TOKEN) {
      warn("RAILWAY_TOKEN is not set — the CLI will use the project linked with `railway link`.");
    }
    info("Railway builds the uploaded sources; watch the build logs it streams back.");
    run("railway", ["up", ".", "--service", app, ...extraArgs], { cwd: stageDir, dryRun });
  },

  notes: [
    "First deploy: create the service in the Railway dashboard (or `railway add --service <name>`)",
    "and link it with `railway link`. Set the service's domain afterwards with `railway domain`.",
    "The service's Root Directory setting must stay empty — the stage is uploaded as its own root.",
  ],
};
