import { fail, info, step, warn } from "../lib/log.mjs";
import { hasCommand, run } from "../lib/run.mjs";

/** Astro adapter for Vercel. Peers with astro ^7. */
const VERCEL_ADAPTER = "^11.0.0";

/**
 * Vercel target: Astro SSR on Vercel Functions (Node.js runtime, Fluid compute).
 *
 * Vercel builds the uploaded sources itself, but unlike Railway the built server does not run next
 * to the plugin's files: the function is assembled from traced modules and runs in `/var/task`.
 * Everything the plugin runtime reads from disk per request — `package.json`, `README.md`,
 * `qrtl.config.*`, the generated `src/qrtl-plugin/*.json`, `skills/`, `agents/`, `public/` and the
 * docs SPA vendored in `@quartal/plugin` — must therefore be forced into the function via the
 * adapter's `includeFiles`. The generated Astro config computes that list at build time (see
 * `astroImports` below), and `@quartal/plugin` resolves its root back to the function's cwd at
 * runtime (`Helpers.resolvePluginRoot`), since the absolute path baked in at build time does not
 * exist in `/var/task`.
 *
 * Requires `@quartal/plugin` > 0.8.0 (the `resolvePluginRoot` fallback). Until that is published,
 * deploy with `--link local` so the stage vendors the fixed workspace build.
 */
export default {
  id: "vercel",
  title: "Vercel",
  adapterName: "@astrojs/vercel",
  dependencies: { "@astrojs/vercel": VERCEL_ADAPTER },
  /** Not used by Vercel (functions have no start script), but keeps `npm start` meaningful locally. */
  startCommand: "node ./dist/server/entry.mjs",
  buildsLocally: false,
  astroImports: [
    `import vercel from "@astrojs/vercel";`,
    `import { existsSync, readdirSync } from "node:fs";`,
    `import { join } from "node:path";`,
    ``,
    `// The plugin runtime reads these from disk per request; a Vercel function only contains traced`,
    `// modules, so every file is forced in via includeFiles (paths relative to this config file).`,
    `const walk = (dir) =>`,
    `  existsSync(dir)`,
    `    ? readdirSync(dir, { withFileTypes: true }).flatMap((e) =>`,
    `        e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)])`,
    `    : [];`,
    `const includeFiles = [`,
    `  "package.json",`,
    `  "README.md",`,
    `  ...["qrtl.config.json", "qrtl.config.ts", "qrtl.config.mjs", "qrtl.config.js"].filter((f) => existsSync(f)),`,
    `  // Generated by the qrtl codegen during this same build — fixed names, copied after the build.`,
    `  ...["tools.json", "open-api.json", "types.json", "contents.json", "mcp-tools.json", "mcp-prompts.json"]`,
    `    .map((f) => join("src", "qrtl-plugin", f)),`,
    `  ...walk("skills"),`,
    `  ...walk("agents"),`,
    `  ...walk("public"),`,
    `  // The docs SPA that @quartal/plugin serves at "/" — vendored files, never require()d, so the`,
    `  // module tracer cannot see them.`,
    `  ...walk(join("node_modules", "@quartal", "plugin", "static", "plugin-docs-web")),`,
    `];`,
  ],
  astroOverrides: [`adapter: vercel({ includeFiles }),`],

  files: ({ project }) => ({
    "vercel.json": `${JSON.stringify(
      {
        $schema: "https://openapi.vercel.sh/vercel.json",
        framework: "astro",
      },
      null,
      2,
    )}\n`,
    // vendor/ (from --link local) must upload; build output and installs must not.
    ".vercelignore": `node_modules\ndist\n.astro\n.vercel\n`,
    ".gitignore": `node_modules/\ndist/\n.astro/\n.vercel/\n`,
    "DEPLOY.md": [
      `# ${project.name} — Vercel stage`,
      ``,
      `Generated by \`deployment/deploy.mjs vercel ${project.name}\`. Do not edit; re-run the script.`,
      ``,
      `Vercel builds this directory remotely (\`npm install\` -> \`astro build\`) and serves the SSR`,
      `routes from a Node function. \`astro.config.mjs\` forces the plugin's runtime files (skills,`,
      `agents, public/, qrtl-plugin artifacts, docs SPA) into the function via \`includeFiles\`.`,
      ``,
      `Deploys are previews by default; pass \`--prod\` through (\`-- --prod\`) for production.`,
      ``,
    ].join("\n"),
  }),

  /**
   * Links the stage to the Vercel project (creating it on first use) and uploads the sources.
   * Authenticate with `npx vercel login`, or set VERCEL_TOKEN (forwarded as --token).
   */
  deploy({ stageDir, app, org, dryRun, extraArgs }) {
    step(`Deploying to Vercel project "${app}"${org ? ` (scope: ${org})` : ""}`);
    if (!dryRun && !hasCommand("npx", ["--version"])) fail("npx not found — Node 22+ is required.");

    const auth = process.env.VERCEL_TOKEN ? ["--token", process.env.VERCEL_TOKEN] : [];
    if (!auth.length) {
      warn("VERCEL_TOKEN is not set — the CLI will use the login from `npx vercel login`.");
    }
    const scope = org ? ["--scope", org] : [];

    run("npx", ["vercel", "link", "--yes", "--project", app, ...scope, ...auth], { cwd: stageDir, dryRun });
    info("Vercel builds the uploaded sources; the CLI streams the build log and prints the URL.");
    run("npx", ["vercel", "deploy", "--yes", ...scope, ...auth, ...extraArgs], { cwd: stageDir, dryRun });
  },

  notes: [
    "Deploys are previews; production is `-- --prod`. The first deploy creates the project.",
    "Until @quartal/plugin > 0.8.0 is on npm, deploy with `--link local` (after `pnpm build:libs`):",
    "the published 0.8.0 runtime resolves the baked build path and 500s inside a Vercel function.",
    "Auth plugins: set the OAUTH_* env vars with `npx vercel env add` (or the dashboard) per",
    "environment before the deploy that needs them.",
    "`--build` pre-flights locally: it produces .vercel/output/, so you can inspect the function",
    "bundle (functions/_render.func/) before spending a remote build.",
  ],
};
