import { fail, info, step, warn } from "../lib/log.mjs";
import { hasCommand, run } from "../lib/run.mjs";

/** Astro adapter for Vercel. Peers with astro ^7. */
const VERCEL_ADAPTER = "^11.0.0";

/**
 * Vercel target: Astro SSR on Vercel Functions (Node.js runtime, Fluid compute).
 *
 * Vercel builds the uploaded sources itself, but unlike Railway the built server does not run next
 * to the plugin's files: the function is assembled from traced modules and runs in `/var/task`.
 * That needs no configuration any more: the codegen's `artifacts.ts` module carries the generated
 * metadata, manifest, qrtl.config, widget entries AND the skills/agents/README file map inside the
 * server bundle, the docs UI shell is fetched from the Quartal Plugins website at runtime, and
 * `public/` is served by Vercel's static layer (Astro ships it into the static output). So the
 * adapter needs no `includeFiles`, and `@quartal/plugin` resolves its root back to the function's
 * cwd at runtime (`Helpers.resolvePluginRoot`) purely as a safety net.
 *
 * Requires `@quartal/plugin` > 0.8.0 (artifacts module + file map + docs shell). Until that is
 * published, deploy with `--link local` so the stage vendors the fixed workspace build.
 */
export default {
  id: "vercel",
  title: "Vercel",
  adapterName: "@astrojs/vercel",
  dependencies: { "@astrojs/vercel": VERCEL_ADAPTER },
  /** Not used by Vercel (functions have no start script), but keeps `npm start` meaningful locally. */
  startCommand: "node ./dist/server/entry.mjs",
  buildsLocally: false,
  astroImports: [`import vercel from "@astrojs/vercel";`],
  astroOverrides: [`adapter: vercel(),`],

  files: ({ project }) => ({
    "vercel.json": `${JSON.stringify(
      {
        $schema: "https://openapi.vercel.sh/vercel.json",
        framework: "astro",
      },
      null,
      2,
    )}\n`,
    // vendor/ (from --link local) must upload; build output and installs must not.
    ".vercelignore": `node_modules\ndist\n.astro\n.vercel\n`,
    ".gitignore": `node_modules/\ndist/\n.astro/\n.vercel/\n`,
    "DEPLOY.md": [
      `# ${project.name} — Vercel stage`,
      ``,
      `Generated by \`deployment/deploy.mjs vercel ${project.name}\`. Do not edit; re-run the script.`,
      ``,
      `Vercel builds this directory remotely (\`npm install\` -> \`astro build\`) and serves the SSR`,
      `routes from a Node function. \`astro.config.mjs\` forces the plugin's runtime files (skills,`,
      `agents, public/, qrtl-plugin artifacts, docs SPA) into the function via \`includeFiles\`.`,
      ``,
      `Deploys are previews by default; pass \`--prod\` through (\`-- --prod\`) for production.`,
      ``,
    ].join("\n"),
  }),

  /**
   * Links the stage to the Vercel project (creating it on first use) and uploads the sources.
   * Authenticate with `npx vercel login`, or set VERCEL_TOKEN (forwarded as --token).
   */
  deploy({ stageDir, app, org, dryRun, extraArgs }) {
    step(`Deploying to Vercel project "${app}"${org ? ` (scope: ${org})` : ""}`);
    if (!dryRun && !hasCommand("npx", ["--version"])) fail("npx not found — Node 22+ is required.");

    const auth = process.env.VERCEL_TOKEN ? ["--token", process.env.VERCEL_TOKEN] : [];
    if (!auth.length) {
      warn("VERCEL_TOKEN is not set — the CLI will use the login from `npx vercel login`.");
    }
    const scope = org ? ["--scope", org] : [];

    run("npx", ["vercel", "link", "--yes", "--project", app, ...scope, ...auth], { cwd: stageDir, dryRun });
    info("Vercel builds the uploaded sources; the CLI streams the build log and prints the URL.");
    run("npx", ["vercel", "deploy", "--yes", ...scope, ...auth, ...extraArgs], { cwd: stageDir, dryRun });
  },

  notes: [
    "Deploys are previews; production is `-- --prod`. The first deploy creates the project.",
    "Until @quartal/plugin > 0.8.0 is on npm, deploy with `--link local` (after `pnpm build:libs`):",
    "the published 0.8.0 runtime resolves the baked build path and 500s inside a Vercel function.",
    "Auth plugins: set the OAUTH_* env vars with `npx vercel env add` (or the dashboard) per",
    "environment before the deploy that needs them.",
    "`--build` pre-flights locally: it produces .vercel/output/, so you can inspect the function",
    "bundle (functions/_render.func/) before spending a remote build.",
  ],
};
