/** File name of the catch-all route module the integration writes into the `qrtl-plugin/` directory. */
export const CATCH_ALL_ROUTE_FILE = "catchAllRoute.ts";

/**
 * Source of the catch-all Astro route module written into the project. The handler itself lives in
 * `@quartal/plugin/astro/route`; this file only re-exports it so the route's entrypoint is a
 * project file. Vite bundles a route entry from the project as a normal page module, whereas an
 * entry inside `node_modules` is treated as an external dependency and breaks the server build.
 */
export function buildCatchAllRouteSource(): string {
  return [
    `// AUTO-GENERATED by @quartal/plugin — the catch-all Astro route that keeps the plugin's server`,
    `// paths (/plugin.json, /api/*, /mcp, …) in Astro's route table for the host platform's router.`,
    `export { ALL } from "@quartal/plugin/astro/route";`,
    ``,
  ].join("\n");
}
